project_id = "xdmbkflufsfqziixzpxc"

[functions.catalogo-pix-sandbox]
verify_jwt = false

[functions.catalogo-pix-producao]
verify_jwt = false

[functions.mercadopago-oauth-callback]
verify_jwt = false

[functions.catalogo-pedido-pix]
verify_jwt = false

[functions.mercadopago-marketplace-webhook]
verify_jwt = false

[functions.catalogo-pedido-offline]
verify_jwt = false
