-- Somente CI. Sem pg_cron, pg_net, conexoes externas ou dados reais.
-- Usa cron.schedule()/unschedule() inertes: apenas inserem/removem linhas locais.
-- Vault também é completamente sintético. NUNCA executar em produção.
DO $guard$
BEGIN
  IF current_database() <> 'catalogo_ci'
     OR current_setting('app.marketplace_test_scheduler', true) IS DISTINCT FROM 'enabled'
     OR to_regnamespace('cron') IS NOT NULL
     OR to_regnamespace('vault') IS NOT NULL
     OR EXISTS (SELECT 1 FROM pg_extension WHERE extname IN ('pg_cron','pg_net'))
  THEN
    RAISE EXCEPTION 'Mocks Cron/Vault exigem catalogo_ci isolado e opt-in';
  END IF;
END $guard$;

CREATE ROLE anon NOLOGIN;
CREATE ROLE authenticated NOLOGIN;
CREATE ROLE service_role NOLOGIN;

CREATE SCHEMA vault;
CREATE TABLE vault.secrets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text UNIQUE NOT NULL,
  secret text NOT NULL,
  description text
);
CREATE VIEW vault.decrypted_secrets AS
SELECT id, name, secret AS decrypted_secret
FROM vault.secrets;

CREATE FUNCTION vault.create_secret(p_secret text, p_name text, p_description text)
RETURNS uuid LANGUAGE plpgsql AS $vault_stub$
DECLARE v_id uuid;
BEGIN
  INSERT INTO vault.secrets(name, secret, description)
  VALUES (p_name, p_secret, p_description)
  RETURNING id INTO v_id;
  RETURN v_id;
END $vault_stub$;

CREATE SCHEMA cron;
CREATE TABLE cron.job (
  jobid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  jobname text UNIQUE NOT NULL,
  schedule text NOT NULL,
  command text NOT NULL
);

-- CRÍTICO: não executa, não agenda, não interpreta e não transmite o command.
-- Salva APENAS texto em uma tabela descartável.
CREATE FUNCTION cron.schedule(p_jobname text, p_schedule text, p_command text)
RETURNS bigint LANGUAGE plpgsql AS $cron_stub$
DECLARE v_jobid bigint;
BEGIN
  INSERT INTO cron.job(jobname, schedule, command)
  VALUES (p_jobname, p_schedule, p_command)
  RETURNING jobid INTO v_jobid;
  RETURN v_jobid;
END $cron_stub$;

CREATE FUNCTION cron.unschedule(p_jobid bigint)
RETURNS boolean LANGUAGE plpgsql AS $unschedule_stub$
BEGIN
  DELETE FROM cron.job WHERE jobid = p_jobid;
  RETURN FOUND;
END $unschedule_stub$;
