-- SOMENTE TESTES LOCAIS. NUNCA executar em producao.
-- Reconstroi tabelas legadas anteriores ao primeiro migration versionado.
-- Executar em instancia Supabase DESCARTAVEL antes das migrations, apos auth existir.
-- Exige opt-in EXPLICITO por sessao: SET app.marketplace_test_baseline = 'enabled';
-- O opt-in NAO substitui isolamento de rede/credenciais e validacao do alvo.
DO $guard$
BEGIN
  IF current_setting('app.marketplace_test_baseline', true) IS DISTINCT FROM 'enabled'
     OR current_database() <> 'catalogo_ci'
     OR to_regclass('auth.users') IS NULL
     OR to_regclass('public.avaliacoes') IS NOT NULL
     OR to_regclass('public.cadastros_comercios') IS NOT NULL
     OR to_regclass('public.mural_cadastros') IS NOT NULL
  THEN
    RAISE EXCEPTION 'Baseline legado exige Supabase local descartavel sem tabelas legadas';
  END IF;
END $guard$;

CREATE TABLE public.avaliacoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  local_id text NOT NULL,
  usuario_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nome_usuario text NOT NULL,
  nota integer NOT NULL CONSTRAINT avaliacoes_nota_check CHECK (nota BETWEEN 1 AND 5),
  comentario text NOT NULL CONSTRAINT avaliacoes_comentario_check CHECK (char_length(comentario) BETWEEN 1 AND 500),
  criado_em timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX avaliacoes_local_id_idx ON public.avaliacoes(local_id);
CREATE INDEX avaliacoes_usuario_id_idx ON public.avaliacoes(usuario_id);
ALTER TABLE public.avaliacoes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Todos podem visualizar avaliações" ON public.avaliacoes FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Usuários podem criar avaliações" ON public.avaliacoes FOR INSERT TO authenticated WITH CHECK ((SELECT auth.uid()) = usuario_id);
CREATE POLICY "Usuários podem editar suas avaliações" ON public.avaliacoes FOR UPDATE TO authenticated USING ((SELECT auth.uid()) = usuario_id) WITH CHECK ((SELECT auth.uid()) = usuario_id);
CREATE POLICY "Usuários podem excluir suas avaliações" ON public.avaliacoes FOR DELETE TO authenticated USING ((SELECT auth.uid()) = usuario_id);

CREATE TABLE public.cadastros_comercios (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  telefone_usuario text NOT NULL,
  nome text, categoria text, whatsapp text, instagram text,
  endereco text, horario text, descricao text,
  latitude double precision, longitude double precision,
  imagem_url text,
  etapa text NOT NULL DEFAULT 'inicio',
  status text NOT NULL DEFAULT 'em_andamento'
    CONSTRAINT cadastros_comercios_status_check
    CHECK (status IN ('em_andamento','pendente','aprovado','rejeitado')),
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  revisado_por uuid, revisado_em timestamptz, motivo_rejeicao text,
  usuario_id uuid REFERENCES auth.users(id),
  tipo text DEFAULT 'novo_comercio',
  local_id text,
  imagens jsonb DEFAULT '[]'::jsonb
);
-- A etapa inicial e historicamente 'inicio', embora o CHECK atual nao a inclua.
-- Evitar adicionar a restricao de etapa ate verificar a ordem historica das alteracoes.
CREATE INDEX cadastros_comercios_status_idx ON public.cadastros_comercios(status);
CREATE INDEX cadastros_comercios_telefone_idx ON public.cadastros_comercios(telefone_usuario);
CREATE INDEX idx_cadastros_comercios_local_id ON public.cadastros_comercios(local_id);
CREATE INDEX idx_cadastros_comercios_tipo ON public.cadastros_comercios(tipo);
CREATE INDEX idx_cadastros_comercios_usuario_id ON public.cadastros_comercios(usuario_id);
ALTER TABLE public.cadastros_comercios ENABLE ROW LEVEL SECURITY;
CREATE POLICY cadastros_comercios_usuario_select ON public.cadastros_comercios
  FOR SELECT TO authenticated USING ((SELECT auth.uid()) = usuario_id);
-- A policy de INSERT sera criada pela migration 20261006111500.
-- Politicas administrativas com ID real nao sao transportadas ao teste.

-- Tabela legada do mural, confirmada via metadados (sem copiar registros).
-- O status historico pode ter 'aprovado'/'recusado' antes da primeira migration;
-- a constraint definitiva sera criada pela propria migration.
CREATE TABLE public.mural_cadastros (
  id text PRIMARY KEY,
  usuario_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nome text NOT NULL,
  categoria text NOT NULL,
  descricao text DEFAULT '',
  sobre text DEFAULT '',
  instagram text DEFAULT '',
  imagem text DEFAULT '',
  imagens jsonb DEFAULT '[]'::jsonb,
  status text NOT NULL DEFAULT 'pendente',
  motivo_recusa text DEFAULT '',
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX mural_cadastros_status_idx ON public.mural_cadastros(status);
CREATE INDEX mural_cadastros_usuario_id_idx ON public.mural_cadastros(usuario_id);
ALTER TABLE public.mural_cadastros ENABLE ROW LEVEL SECURITY;

-- Seed sintetica, necessaria ao DO de verificacao da primeira migration.
-- Nao inclui informacoes de contato reais nem replica cadastros de producao.
INSERT INTO public.cadastros_comercios (telefone_usuario,nome,status,etapa,local_id)
VALUES ('TESTE-SEM-TELEFONE','PedroX do Grau','aprovado','formulario_web',NULL);
